export const GET_USER_LOCALSTORAGE_SUCCESS = 'GET_USER_LOCALSTORAGE_SUCCESS';
export const GET_USER_LOCALSTORAGE_REQUEST = 'GET_USER_LOCALSTORAGE_REQUEST';
export const GET_USER_LOCALSTORAGE_ERROR = 'GET_USER_LOCALSTORAGE_ERROR';
